import { TelegramMethod, TelegramParam, TelegramType } from './types';

// Sidebar structure matching official Telegram Bot API docs
export const sidebarGroups = {
  sections: [
    {
      label: 'Getting updates',
      items: [
        { name: 'Update', kind: 'type' as const },
        { name: 'getUpdates', kind: 'method' as const },
        { name: 'setWebhook', kind: 'method' as const },
        { name: 'deleteWebhook', kind: 'method' as const },
        { name: 'getWebhookInfo', kind: 'method' as const },
        { name: 'WebhookInfo', kind: 'type' as const },
      ],
    },
    {
      label: 'Available types',
      items: [
        { name: 'User', kind: 'type' as const },
        { name: 'Chat', kind: 'type' as const },
        { name: 'ChatFullInfo', kind: 'type' as const },
        { name: 'Message', kind: 'type' as const },
        { name: 'MessageId', kind: 'type' as const },
        { name: 'InaccessibleMessage', kind: 'type' as const },
        { name: 'MaybeInaccessibleMessage', kind: 'type' as const },
        { name: 'MessageEntity', kind: 'type' as const },
        { name: 'TextQuote', kind: 'type' as const },
        { name: 'ExternalReplyInfo', kind: 'type' as const },
        { name: 'ReplyParameters', kind: 'type' as const },
        { name: 'MessageOrigin', kind: 'type' as const },
        { name: 'MessageOriginUser', kind: 'type' as const },
        { name: 'MessageOriginHiddenUser', kind: 'type' as const },
        { name: 'MessageOriginChat', kind: 'type' as const },
        { name: 'MessageOriginChannel', kind: 'type' as const },
        { name: 'LinkPreviewOptions', kind: 'type' as const },
        { name: 'PhotoSize', kind: 'type' as const },
        { name: 'Animation', kind: 'type' as const },
        { name: 'Audio', kind: 'type' as const },
        { name: 'Document', kind: 'type' as const },
        { name: 'Story', kind: 'type' as const },
        { name: 'Video', kind: 'type' as const },
        { name: 'VideoNote', kind: 'type' as const },
        { name: 'Voice', kind: 'type' as const },
        { name: 'PaidMediaInfo', kind: 'type' as const },
        { name: 'PaidMediaPreview', kind: 'type' as const },
        { name: 'PaidMediaPhoto', kind: 'type' as const },
        { name: 'PaidMediaVideo', kind: 'type' as const },
        { name: 'Contact', kind: 'type' as const },
        { name: 'Dice', kind: 'type' as const },
        { name: 'PollOption', kind: 'type' as const },
        { name: 'PollAnswer', kind: 'type' as const },
        { name: 'Poll', kind: 'type' as const },
        { name: 'Location', kind: 'type' as const },
        { name: 'Venue', kind: 'type' as const },
        { name: 'WebAppData', kind: 'type' as const },
        { name: 'ProximityAlertTriggered', kind: 'type' as const },
        { name: 'MessageAutoDeleteTimerChanged', kind: 'type' as const },
        { name: 'ChatBoostAdded', kind: 'type' as const },
        { name: 'BackgroundFill', kind: 'type' as const },
        { name: 'BackgroundType', kind: 'type' as const },
        { name: 'ChatBackground', kind: 'type' as const },
        { name: 'ForumTopicCreated', kind: 'type' as const },
        { name: 'ForumTopicClosed', kind: 'type' as const },
        { name: 'ForumTopicEdited', kind: 'type' as const },
        { name: 'ForumTopicReopened', kind: 'type' as const },
        { name: 'GeneralForumTopicHidden', kind: 'type' as const },
        { name: 'GeneralForumTopicUnhidden', kind: 'type' as const },
        { name: 'SharedUser', kind: 'type' as const },
        { name: 'UsersShared', kind: 'type' as const },
        { name: 'ChatShared', kind: 'type' as const },
        { name: 'WriteAccessAllowed', kind: 'type' as const },
        { name: 'VideoChatScheduled', kind: 'type' as const },
        { name: 'VideoChatStarted', kind: 'type' as const },
        { name: 'VideoChatEnded', kind: 'type' as const },
        { name: 'VideoChatParticipantsInvited', kind: 'type' as const },
        { name: 'GiveawayCreated', kind: 'type' as const },
        { name: 'Giveaway', kind: 'type' as const },
        { name: 'GiveawayWinners', kind: 'type' as const },
        { name: 'GiveawayCompleted', kind: 'type' as const },
        { name: 'UserProfilePhotos', kind: 'type' as const },
        { name: 'File', kind: 'type' as const },
        { name: 'WebAppInfo', kind: 'type' as const },
        { name: 'ReplyKeyboardMarkup', kind: 'type' as const },
        { name: 'KeyboardButton', kind: 'type' as const },
        { name: 'KeyboardButtonRequestUsers', kind: 'type' as const },
        { name: 'KeyboardButtonRequestChat', kind: 'type' as const },
        { name: 'KeyboardButtonPollType', kind: 'type' as const },
        { name: 'ReplyKeyboardRemove', kind: 'type' as const },
        { name: 'InlineKeyboardMarkup', kind: 'type' as const },
        { name: 'InlineKeyboardButton', kind: 'type' as const },
        { name: 'LoginUrl', kind: 'type' as const },
        { name: 'SwitchInlineQueryChosenChat', kind: 'type' as const },
        { name: 'CopyTextButton', kind: 'type' as const },
        { name: 'CallbackQuery', kind: 'type' as const },
        { name: 'ForceReply', kind: 'type' as const },
        { name: 'ChatPhoto', kind: 'type' as const },
        { name: 'ChatInviteLink', kind: 'type' as const },
        { name: 'ChatAdministratorRights', kind: 'type' as const },
        { name: 'ChatMemberUpdated', kind: 'type' as const },
        { name: 'ChatMember', kind: 'type' as const },
        { name: 'ChatMemberOwner', kind: 'type' as const },
        { name: 'ChatMemberAdministrator', kind: 'type' as const },
        { name: 'ChatMemberMember', kind: 'type' as const },
        { name: 'ChatMemberRestricted', kind: 'type' as const },
        { name: 'ChatMemberLeft', kind: 'type' as const },
        { name: 'ChatMemberBanned', kind: 'type' as const },
        { name: 'ChatJoinRequest', kind: 'type' as const },
        { name: 'ChatPermissions', kind: 'type' as const },
        { name: 'Birthdate', kind: 'type' as const },
        { name: 'BusinessIntro', kind: 'type' as const },
        { name: 'BusinessLocation', kind: 'type' as const },
        { name: 'BusinessOpeningHoursInterval', kind: 'type' as const },
        { name: 'BusinessOpeningHours', kind: 'type' as const },
        { name: 'ChatLocation', kind: 'type' as const },
        { name: 'ReactionType', kind: 'type' as const },
        { name: 'ReactionCount', kind: 'type' as const },
        { name: 'MessageReactionUpdated', kind: 'type' as const },
        { name: 'MessageReactionCountUpdated', kind: 'type' as const },
        { name: 'ForumTopic', kind: 'type' as const },
        { name: 'BotCommand', kind: 'type' as const },
        { name: 'BotCommandScope', kind: 'type' as const },
        { name: 'BotName', kind: 'type' as const },
        { name: 'BotDescription', kind: 'type' as const },
        { name: 'BotShortDescription', kind: 'type' as const },
        { name: 'MenuButton', kind: 'type' as const },
        { name: 'ChatBoostSource', kind: 'type' as const },
        { name: 'ChatBoost', kind: 'type' as const },
        { name: 'ChatBoostUpdated', kind: 'type' as const },
        { name: 'ChatBoostRemoved', kind: 'type' as const },
        { name: 'UserChatBoosts', kind: 'type' as const },
        { name: 'BusinessConnection', kind: 'type' as const },
        { name: 'BusinessMessagesDeleted', kind: 'type' as const },
        { name: 'ResponseParameters', kind: 'type' as const },
        { name: 'InputMedia', kind: 'type' as const },
        { name: 'InputMediaPhoto', kind: 'type' as const },
        { name: 'InputMediaVideo', kind: 'type' as const },
        { name: 'InputMediaAnimation', kind: 'type' as const },
        { name: 'InputMediaAudio', kind: 'type' as const },
        { name: 'InputMediaDocument', kind: 'type' as const },
        { name: 'InputFile', kind: 'type' as const },
        { name: 'InputPaidMedia', kind: 'type' as const },
        { name: 'InputPaidMediaPhoto', kind: 'type' as const },
        { name: 'InputPaidMediaVideo', kind: 'type' as const },
      ],
    },
    {
      label: 'Available methods',
      items: [
        { name: 'sendMessage', kind: 'method' as const },
        { name: 'forwardMessage', kind: 'method' as const },
        { name: 'forwardMessages', kind: 'method' as const },
        { name: 'copyMessage', kind: 'method' as const },
        { name: 'copyMessages', kind: 'method' as const },
        { name: 'sendPhoto', kind: 'method' as const },
        { name: 'sendAudio', kind: 'method' as const },
        { name: 'sendDocument', kind: 'method' as const },
        { name: 'sendVideo', kind: 'method' as const },
        { name: 'sendAnimation', kind: 'method' as const },
        { name: 'sendVoice', kind: 'method' as const },
        { name: 'sendVideoNote', kind: 'method' as const },
        { name: 'sendPaidMedia', kind: 'method' as const },
        { name: 'sendMediaGroup', kind: 'method' as const },
        { name: 'sendLocation', kind: 'method' as const },
        { name: 'sendVenue', kind: 'method' as const },
        { name: 'sendContact', kind: 'method' as const },
        { name: 'sendPoll', kind: 'method' as const },
        { name: 'sendDice', kind: 'method' as const },
        { name: 'sendChatAction', kind: 'method' as const },
        { name: 'setMessageReaction', kind: 'method' as const },
        { name: 'getUserProfilePhotos', kind: 'method' as const },
        { name: 'getFile', kind: 'method' as const },
        { name: 'banChatMember', kind: 'method' as const },
        { name: 'unbanChatMember', kind: 'method' as const },
        { name: 'restrictChatMember', kind: 'method' as const },
        { name: 'promoteChatMember', kind: 'method' as const },
        { name: 'setChatAdministratorCustomTitle', kind: 'method' as const },
        { name: 'banChatSenderChat', kind: 'method' as const },
        { name: 'unbanChatSenderChat', kind: 'method' as const },
        { name: 'setChatPermissions', kind: 'method' as const },
        { name: 'exportChatInviteLink', kind: 'method' as const },
        { name: 'createChatInviteLink', kind: 'method' as const },
        { name: 'editChatInviteLink', kind: 'method' as const },
        { name: 'createChatSubscriptionInviteLink', kind: 'method' as const },
        { name: 'editChatSubscriptionInviteLink', kind: 'method' as const },
        { name: 'revokeChatInviteLink', kind: 'method' as const },
        { name: 'approveChatJoinRequest', kind: 'method' as const },
        { name: 'declineChatJoinRequest', kind: 'method' as const },
        { name: 'setChatPhoto', kind: 'method' as const },
        { name: 'deleteChatPhoto', kind: 'method' as const },
        { name: 'setChatTitle', kind: 'method' as const },
        { name: 'setChatDescription', kind: 'method' as const },
        { name: 'pinChatMessage', kind: 'method' as const },
        { name: 'unpinChatMessage', kind: 'method' as const },
        { name: 'unpinAllChatMessages', kind: 'method' as const },
        { name: 'leaveChat', kind: 'method' as const },
        { name: 'getChat', kind: 'method' as const },
        { name: 'getChatAdministrators', kind: 'method' as const },
        { name: 'getChatMemberCount', kind: 'method' as const },
        { name: 'getChatMember', kind: 'method' as const },
        { name: 'setChatStickerSet', kind: 'method' as const },
        { name: 'deleteChatStickerSet', kind: 'method' as const },
        { name: 'getForumTopicIconStickers', kind: 'method' as const },
        { name: 'createForumTopic', kind: 'method' as const },
        { name: 'editForumTopic', kind: 'method' as const },
        { name: 'closeForumTopic', kind: 'method' as const },
        { name: 'reopenForumTopic', kind: 'method' as const },
        { name: 'deleteForumTopic', kind: 'method' as const },
        { name: 'unpinAllForumTopicMessages', kind: 'method' as const },
        { name: 'editGeneralForumTopic', kind: 'method' as const },
        { name: 'closeGeneralForumTopic', kind: 'method' as const },
        { name: 'reopenGeneralForumTopic', kind: 'method' as const },
        { name: 'hideGeneralForumTopic', kind: 'method' as const },
        { name: 'unhideGeneralForumTopic', kind: 'method' as const },
        { name: 'unpinAllGeneralForumTopicMessages', kind: 'method' as const },
        { name: 'answerCallbackQuery', kind: 'method' as const },
        { name: 'getUserChatBoosts', kind: 'method' as const },
        { name: 'getBusinessConnection', kind: 'method' as const },
        { name: 'setMyCommands', kind: 'method' as const },
        { name: 'deleteMyCommands', kind: 'method' as const },
        { name: 'getMyCommands', kind: 'method' as const },
        { name: 'setMyName', kind: 'method' as const },
        { name: 'getMyName', kind: 'method' as const },
        { name: 'setMyDescription', kind: 'method' as const },
        { name: 'getMyDescription', kind: 'method' as const },
        { name: 'setMyShortDescription', kind: 'method' as const },
        { name: 'getMyShortDescription', kind: 'method' as const },
        { name: 'setChatMenuButton', kind: 'method' as const },
        { name: 'getChatMenuButton', kind: 'method' as const },
        { name: 'setMyDefaultAdministratorRights', kind: 'method' as const },
        { name: 'getMyDefaultAdministratorRights', kind: 'method' as const },
        { name: 'getMe', kind: 'method' as const },
        { name: 'logOut', kind: 'method' as const },
        { name: 'close', kind: 'method' as const },
      ],
    },
    {
      label: 'Updating messages',
      items: [
        { name: 'editMessageText', kind: 'method' as const },
        { name: 'editMessageCaption', kind: 'method' as const },
        { name: 'editMessageMedia', kind: 'method' as const },
        { name: 'editMessageLiveLocation', kind: 'method' as const },
        { name: 'stopMessageLiveLocation', kind: 'method' as const },
        { name: 'editMessageReplyMarkup', kind: 'method' as const },
        { name: 'stopPoll', kind: 'method' as const },
        { name: 'deleteMessage', kind: 'method' as const },
        { name: 'deleteMessages', kind: 'method' as const },
      ],
    },
    {
      label: 'Stickers',
      items: [
        { name: 'Sticker', kind: 'type' as const },
        { name: 'StickerSet', kind: 'type' as const },
        { name: 'MaskPosition', kind: 'type' as const },
        { name: 'InputSticker', kind: 'type' as const },
        { name: 'sendSticker', kind: 'method' as const },
        { name: 'getStickerSet', kind: 'method' as const },
        { name: 'getCustomEmojiStickers', kind: 'method' as const },
        { name: 'uploadStickerFile', kind: 'method' as const },
        { name: 'createNewStickerSet', kind: 'method' as const },
        { name: 'addStickerToSet', kind: 'method' as const },
        { name: 'setStickerPositionInSet', kind: 'method' as const },
        { name: 'deleteStickerFromSet', kind: 'method' as const },
        { name: 'replaceStickerInSet', kind: 'method' as const },
        { name: 'setStickerEmojiList', kind: 'method' as const },
        { name: 'setStickerKeywords', kind: 'method' as const },
        { name: 'setStickerMaskPosition', kind: 'method' as const },
        { name: 'setStickerSetTitle', kind: 'method' as const },
        { name: 'setStickerSetThumbnail', kind: 'method' as const },
        { name: 'setCustomEmojiStickerSetThumbnail', kind: 'method' as const },
        { name: 'deleteStickerSet', kind: 'method' as const },
      ],
    },
    {
      label: 'Inline mode',
      items: [
        { name: 'InlineQuery', kind: 'type' as const },
        { name: 'answerInlineQuery', kind: 'method' as const },
        { name: 'InlineQueryResultsButton', kind: 'type' as const },
        { name: 'InlineQueryResult', kind: 'type' as const },
        { name: 'InlineQueryResultArticle', kind: 'type' as const },
        { name: 'InlineQueryResultPhoto', kind: 'type' as const },
        { name: 'InlineQueryResultGif', kind: 'type' as const },
        { name: 'InlineQueryResultMpeg4Gif', kind: 'type' as const },
        { name: 'InlineQueryResultVideo', kind: 'type' as const },
        { name: 'InlineQueryResultAudio', kind: 'type' as const },
        { name: 'InlineQueryResultVoice', kind: 'type' as const },
        { name: 'InlineQueryResultDocument', kind: 'type' as const },
        { name: 'InlineQueryResultLocation', kind: 'type' as const },
        { name: 'InlineQueryResultVenue', kind: 'type' as const },
        { name: 'InlineQueryResultContact', kind: 'type' as const },
        { name: 'InlineQueryResultGame', kind: 'type' as const },
        { name: 'InlineQueryResultCachedPhoto', kind: 'type' as const },
        { name: 'InlineQueryResultCachedGif', kind: 'type' as const },
        { name: 'InlineQueryResultCachedMpeg4Gif', kind: 'type' as const },
        { name: 'InlineQueryResultCachedSticker', kind: 'type' as const },
        { name: 'InlineQueryResultCachedDocument', kind: 'type' as const },
        { name: 'InlineQueryResultCachedVideo', kind: 'type' as const },
        { name: 'InlineQueryResultCachedVoice', kind: 'type' as const },
        { name: 'InlineQueryResultCachedAudio', kind: 'type' as const },
        { name: 'InputMessageContent', kind: 'type' as const },
        { name: 'InputTextMessageContent', kind: 'type' as const },
        { name: 'InputLocationMessageContent', kind: 'type' as const },
        { name: 'InputVenueMessageContent', kind: 'type' as const },
        { name: 'InputContactMessageContent', kind: 'type' as const },
        { name: 'InputInvoiceMessageContent', kind: 'type' as const },
        { name: 'ChosenInlineResult', kind: 'type' as const },
        { name: 'answerWebAppQuery', kind: 'method' as const },
        { name: 'SentWebAppMessage', kind: 'type' as const },
      ],
    },
    {
      label: 'Payments',
      items: [
        { name: 'sendInvoice', kind: 'method' as const },
        { name: 'createInvoiceLink', kind: 'method' as const },
        { name: 'answerShippingQuery', kind: 'method' as const },
        { name: 'answerPreCheckoutQuery', kind: 'method' as const },
        { name: 'getStarTransactions', kind: 'method' as const },
        { name: 'refundStarPayment', kind: 'method' as const },
        { name: 'LabeledPrice', kind: 'type' as const },
        { name: 'Invoice', kind: 'type' as const },
        { name: 'ShippingAddress', kind: 'type' as const },
        { name: 'OrderInfo', kind: 'type' as const },
        { name: 'ShippingOption', kind: 'type' as const },
        { name: 'SuccessfulPayment', kind: 'type' as const },
        { name: 'RefundedPayment', kind: 'type' as const },
        { name: 'ShippingQuery', kind: 'type' as const },
        { name: 'PreCheckoutQuery', kind: 'type' as const },
        { name: 'PaidMediaPurchased', kind: 'type' as const },
        { name: 'RevenueWithdrawalState', kind: 'type' as const },
        { name: 'TransactionPartner', kind: 'type' as const },
        { name: 'StarTransaction', kind: 'type' as const },
        { name: 'StarTransactions', kind: 'type' as const },
      ],
    },
    {
      label: 'Telegram Passport',
      items: [
        { name: 'PassportData', kind: 'type' as const },
        { name: 'PassportFile', kind: 'type' as const },
        { name: 'EncryptedPassportElement', kind: 'type' as const },
        { name: 'EncryptedCredentials', kind: 'type' as const },
        { name: 'setPassportDataErrors', kind: 'method' as const },
        { name: 'PassportElementError', kind: 'type' as const },
        { name: 'PassportElementErrorDataField', kind: 'type' as const },
        { name: 'PassportElementErrorFrontSide', kind: 'type' as const },
        { name: 'PassportElementErrorReverseSide', kind: 'type' as const },
        { name: 'PassportElementErrorSelfie', kind: 'type' as const },
        { name: 'PassportElementErrorFile', kind: 'type' as const },
        { name: 'PassportElementErrorFiles', kind: 'type' as const },
        { name: 'PassportElementErrorTranslationFile', kind: 'type' as const },
        { name: 'PassportElementErrorTranslationFiles', kind: 'type' as const },
        { name: 'PassportElementErrorUnspecified', kind: 'type' as const },
      ],
    },
    {
      label: 'Games',
      items: [
        { name: 'sendGame', kind: 'method' as const },
        { name: 'Game', kind: 'type' as const },
        { name: 'CallbackGame', kind: 'type' as const },
        { name: 'setGameScore', kind: 'method' as const },
        { name: 'getGameHighScores', kind: 'method' as const },
        { name: 'GameHighScore', kind: 'type' as const },
      ],
    },
  ],
};

export const mockMethods: Record<string, TelegramMethod> = {
  sendMessage: {
    name: 'sendMessage',
    category: 'Available methods',
    description: 'Use this method to send text messages. On success, the sent Message is returned.',
    parameters: [
      { name: 'chat_id', type: 'Integer or String', required: true, description: 'Unique identifier for the target chat or username of the target channel', inputType: 'union', unionTypes: [{ label: 'Numeric ID', inputType: 'number' }, { label: 'Username', inputType: 'text' }] },
      { name: 'text', type: 'String', required: true, description: 'Text of the message to be sent, 1-4096 characters after entities parsing', inputType: 'textarea' },
      { name: 'business_connection_id', type: 'String', required: false, description: 'Unique identifier of the business connection on behalf of which the message will be sent', inputType: 'text' },
      { name: 'message_thread_id', type: 'Integer', required: false, description: 'Unique identifier for the target message thread (topic) of the forum', inputType: 'number' },
      { name: 'parse_mode', type: 'String', required: false, description: 'Mode for parsing entities in the message text', inputType: 'select', options: ['None', 'Markdown', 'MarkdownV2', 'HTML'] },
      { name: 'entities', type: 'Array of MessageEntity', required: false, description: 'A JSON-serialized list of special entities that appear in message text', inputType: 'object', fields: [] },
      { name: 'link_preview_options', type: 'LinkPreviewOptions', required: false, description: 'Link preview generation options for the message', inputType: 'object', fields: [
        { name: 'is_disabled', type: 'Boolean', required: false, description: 'True, if the link preview is disabled', inputType: 'boolean' },
        { name: 'url', type: 'String', required: false, description: 'URL to use for the link preview', inputType: 'text' },
        { name: 'prefer_small_media', type: 'Boolean', required: false, description: 'True, if the media in the link preview is supposed to be shrunk', inputType: 'boolean' },
        { name: 'prefer_large_media', type: 'Boolean', required: false, description: 'True, if the media in the link preview is supposed to be enlarged', inputType: 'boolean' },
        { name: 'show_above_text', type: 'Boolean', required: false, description: 'True, if the link preview must be shown above the message text', inputType: 'boolean' },
      ] },
      { name: 'disable_notification', type: 'Boolean', required: false, description: 'Sends the message silently. Users will receive a notification with no sound.', inputType: 'boolean' },
      { name: 'protect_content', type: 'Boolean', required: false, description: 'Protects the contents of the sent message from forwarding and saving', inputType: 'boolean' },
      { name: 'allow_paid_broadcast', type: 'Boolean', required: false, description: 'Pass True to allow up to 1000 messages per second', inputType: 'boolean' },
      { name: 'message_effect_id', type: 'String', required: false, description: 'Unique identifier of the message effect to be added to the message', inputType: 'text' },
      { name: 'reply_parameters', type: 'ReplyParameters', required: false, description: 'Description of the message to reply to', inputType: 'object', fields: [
        { name: 'message_id', type: 'Integer', required: true, description: 'Identifier of the message that will be replied to', inputType: 'number' },
        { name: 'chat_id', type: 'Integer or String', required: false, description: 'Identifier of the chat containing the message', inputType: 'text' },
        { name: 'allow_sending_without_reply', type: 'Boolean', required: false, description: 'Pass True if the message should be sent even if the specified message to be replied to is not found', inputType: 'boolean' },
        { name: 'quote', type: 'String', required: false, description: 'Quoted part of the message to be replied to', inputType: 'textarea' },
      ] },
      { name: 'reply_markup', type: 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply', required: false, description: 'Additional interface options', inputType: 'union', unionTypes: [
        { label: 'InlineKeyboardMarkup', inputType: 'object' },
        { label: 'ReplyKeyboardMarkup', inputType: 'object' },
        { label: 'ReplyKeyboardRemove', inputType: 'object' },
        { label: 'ForceReply', inputType: 'object' },
      ] },
    ],
  },
  getMe: {
    name: 'getMe',
    category: 'Available methods',
    description: 'A simple method for testing your bot\'s authentication token. Requires no parameters. Returns basic information about the bot in form of a User object.',
    parameters: [],
  },
  getUpdates: {
    name: 'getUpdates',
    category: 'Getting updates',
    description: 'Use this method to receive incoming updates using long polling. Returns an Array of Update objects.',
    parameters: [
      { name: 'offset', type: 'Integer', required: false, description: 'Identifier of the first update to be returned', inputType: 'number' },
      { name: 'limit', type: 'Integer', required: false, description: 'Limits the number of updates to be retrieved. Values between 1-100 are accepted. Defaults to 100.', inputType: 'number' },
      { name: 'timeout', type: 'Integer', required: false, description: 'Timeout in seconds for long polling. Defaults to 0.', inputType: 'number' },
      { name: 'allowed_updates', type: 'Array of String', required: false, description: 'A JSON-serialized list of the update types you want your bot to receive', inputType: 'textarea' },
    ],
  },
};

export const mockTypes: Record<string, TelegramType> = {
  MessageEntity: {
    name: 'MessageEntity',
    description: 'This object represents one special entity in a text message. For example, hashtags, usernames, URLs, etc.',
    fields: [
      { name: 'type', type: 'String', required: true, description: 'Type of the entity. Currently, can be "mention", "hashtag", "cashtag", "bot_command", "url", "email", "phone_number", "bold", "italic", "underline", "strikethrough", "spoiler", "blockquote", "expandable_blockquote", "code", "pre", "text_link", "text_mention", "custom_emoji"' },
      { name: 'offset', type: 'Integer', required: true, description: 'Offset in UTF-16 code units to the start of the entity' },
      { name: 'length', type: 'Integer', required: true, description: 'Length of the entity in UTF-16 code units' },
      { name: 'url', type: 'String', required: false, description: 'For "text_link" only, URL that will be opened after user taps on the text' },
      { name: 'user', type: 'User', required: false, description: 'For "text_mention" only, the mentioned user' },
      { name: 'language', type: 'String', required: false, description: 'For "pre" only, the programming language of the entity text' },
      { name: 'custom_emoji_id', type: 'String', required: false, description: 'For "custom_emoji" only, unique identifier of the custom emoji' },
    ],
    example: { type: 'bold', offset: 0, length: 5 },
    relatedTypes: ['User', 'Message'],
    usedByMethods: ['sendMessage', 'editMessageText', 'sendPhoto'],
  },
  User: {
    name: 'User',
    description: 'This object represents a Telegram user or bot.',
    fields: [
      { name: 'id', type: 'Integer', required: true, description: 'Unique identifier for this user or bot' },
      { name: 'is_bot', type: 'Boolean', required: true, description: 'True, if this user is a bot' },
      { name: 'first_name', type: 'String', required: true, description: 'User\'s or bot\'s first name' },
      { name: 'last_name', type: 'String', required: false, description: 'User\'s or bot\'s last name' },
      { name: 'username', type: 'String', required: false, description: 'User\'s or bot\'s username' },
      { name: 'language_code', type: 'String', required: false, description: 'IETF language tag of the user\'s language' },
      { name: 'is_premium', type: 'Boolean', required: false, description: 'True, if this user is a Telegram Premium user' },
      { name: 'added_to_attachment_menu', type: 'Boolean', required: false, description: 'True, if this user added the bot to the attachment menu' },
      { name: 'can_join_groups', type: 'Boolean', required: false, description: 'True, if the bot can be invited to groups' },
      { name: 'can_read_all_group_messages', type: 'Boolean', required: false, description: 'True, if privacy mode is disabled for the bot' },
      { name: 'supports_inline_queries', type: 'Boolean', required: false, description: 'True, if the bot supports inline queries' },
    ],
    example: { id: 123456789, is_bot: true, first_name: 'TestBot', username: 'test_bot' },
    relatedTypes: ['Chat', 'Message', 'ChatMember'],
    usedByMethods: ['getMe', 'getChat', 'getChatMember'],
  },
};

export const mockSuccessResponse = {
  ok: true,
  result: {
    message_id: 42,
    from: { id: 123456789, is_bot: true, first_name: "TestBot", username: "test_bot" },
    chat: { id: -1001234567890, title: "Test Group", type: "supergroup" },
    date: 1712345678,
    text: "Hello, World!",
  },
};

export const mockErrorResponse = {
  ok: false,
  error_code: 400,
  description: "Bad Request: chat not found",
};
