import { implementedMethods } from "@/methods";

const gettingUpdatesMethods = [
  "getUpdates",
  "setWebhook",
  "deleteWebhook",
  "getWebhookInfo",
];

const updatingMessagesMethods = [
  "editMessageText",
  "editMessageCaption",
  "editMessageMedia",
  "editMessageLiveLocation",
  "stopMessageLiveLocation",
  "editMessageReplyMarkup",
  "editMessageChecklist",
  "stopPoll",
  "deleteMessage",
  "deleteMessages",
  "approveSuggestedPost",
  "declineSuggestedPost",
];

const stickerMethods = [
  "sendSticker",
  "getStickerSet",
  "getCustomEmojiStickers",
  "uploadStickerFile",
  "createNewStickerSet",
  "addStickerToSet",
  "setStickerPositionInSet",
  "deleteStickerFromSet",
  "replaceStickerInSet",
  "setStickerEmojiList",
  "setStickerKeywords",
  "setStickerMaskPosition",
  "setStickerSetTitle",
  "setStickerSetThumbnail",
  "setCustomEmojiStickerSetThumbnail",
  "deleteStickerSet",
];

const inlineModeMethods = [
  "answerInlineQuery",
  "answerWebAppQuery",
  "savePreparedInlineMessage",
  "savePreparedKeyboardButton",
];

const paymentMethods = [
  "sendInvoice",
  "createInvoiceLink",
  "answerShippingQuery",
  "answerPreCheckoutQuery",
];

const telegramPassportMethods = ["setPassportDataErrors"];

const gameMethods = ["sendGame", "setGameScore", "getGameHighScores"];
const generatedTypeNames = [
  "AcceptedGiftTypes",
  "AffiliateInfo",
  "Animation",
  "Audio",
  "BackgroundFill",
  "BackgroundFillFreeformGradient",
  "BackgroundFillGradient",
  "BackgroundFillSolid",
  "BackgroundType",
  "BackgroundTypeChatTheme",
  "BackgroundTypeFill",
  "BackgroundTypePattern",
  "BackgroundTypeWallpaper",
  "Birthdate",
  "BotCommand",
  "BotCommandScope",
  "BotCommandScopeAllChatAdministrators",
  "BotCommandScopeAllGroupChats",
  "BotCommandScopeAllPrivateChats",
  "BotCommandScopeChat",
  "BotCommandScopeChatAdministrators",
  "BotCommandScopeChatMember",
  "BotCommandScopeDefault",
  "BotDescription",
  "BotName",
  "BotShortDescription",
  "BusinessBotRights",
  "BusinessConnection",
  "BusinessIntro",
  "BusinessLocation",
  "BusinessMessagesDeleted",
  "BusinessOpeningHours",
  "BusinessOpeningHoursInterval",
  "CallbackGame",
  "CallbackQuery",
  "Chat",
  "ChatAdministratorRights",
  "ChatBackground",
  "ChatBoost",
  "ChatBoostAdded",
  "ChatBoostRemoved",
  "ChatBoostSource",
  "ChatBoostSourceGiftCode",
  "ChatBoostSourceGiveaway",
  "ChatBoostSourcePremium",
  "ChatBoostUpdated",
  "ChatFullInfo",
  "ChatInviteLink",
  "ChatJoinRequest",
  "ChatLocation",
  "ChatMember",
  "ChatMemberAdministrator",
  "ChatMemberBanned",
  "ChatMemberLeft",
  "ChatMemberMember",
  "ChatMemberOwner",
  "ChatMemberRestricted",
  "ChatMemberUpdated",
  "ChatOwnerChanged",
  "ChatOwnerLeft",
  "ChatPermissions",
  "ChatPhoto",
  "ChatShared",
  "Checklist",
  "ChecklistTask",
  "ChecklistTasksAdded",
  "ChecklistTasksDone",
  "ChosenInlineResult",
  "Contact",
  "CopyTextButton",
  "Dice",
  "DirectMessagePriceChanged",
  "DirectMessagesTopic",
  "Document",
  "EncryptedCredentials",
  "EncryptedPassportElement",
  "ExternalReplyInfo",
  "File",
  "ForceReply",
  "ForumTopic",
  "ForumTopicClosed",
  "ForumTopicCreated",
  "ForumTopicEdited",
  "ForumTopicReopened",
  "Game",
  "GameHighScore",
  "GeneralForumTopicHidden",
  "GeneralForumTopicUnhidden",
  "Gift",
  "GiftBackground",
  "GiftInfo",
  "Gifts",
  "Giveaway",
  "GiveawayCompleted",
  "GiveawayCreated",
  "GiveawayWinners",
  "InaccessibleMessage",
  "InlineKeyboardButton",
  "InlineKeyboardMarkup",
  "InlineQuery",
  "InlineQueryResult",
  "InlineQueryResultArticle",
  "InlineQueryResultAudio",
  "InlineQueryResultCachedAudio",
  "InlineQueryResultCachedDocument",
  "InlineQueryResultCachedGif",
  "InlineQueryResultCachedMpeg4Gif",
  "InlineQueryResultCachedPhoto",
  "InlineQueryResultCachedSticker",
  "InlineQueryResultCachedVideo",
  "InlineQueryResultCachedVoice",
  "InlineQueryResultContact",
  "InlineQueryResultDocument",
  "InlineQueryResultGame",
  "InlineQueryResultGif",
  "InlineQueryResultLocation",
  "InlineQueryResultMpeg4Gif",
  "InlineQueryResultPhoto",
  "InlineQueryResultsButton",
  "InlineQueryResultVenue",
  "InlineQueryResultVideo",
  "InlineQueryResultVoice",
  "InputChecklist",
  "InputChecklistTask",
  "InputContactMessageContent",
  "InputFile",
  "InputInvoiceMessageContent",
  "InputLocationMessageContent",
  "InputMedia",
  "InputMediaAnimation",
  "InputMediaAudio",
  "InputMediaDocument",
  "InputMediaPhoto",
  "InputMediaVideo",
  "InputMessageContent",
  "InputPaidMedia",
  "InputPaidMediaPhoto",
  "InputPaidMediaVideo",
  "InputPollOption",
  "InputProfilePhoto",
  "InputProfilePhotoAnimated",
  "InputProfilePhotoStatic",
  "InputSticker",
  "InputStoryContent",
  "InputStoryContentPhoto",
  "InputStoryContentVideo",
  "InputTextMessageContent",
  "InputVenueMessageContent",
  "Invoice",
  "KeyboardButton",
  "KeyboardButtonPollType",
  "KeyboardButtonRequestChat",
  "KeyboardButtonRequestManagedBot",
  "KeyboardButtonRequestUsers",
  "LabeledPrice",
  "LinkPreviewOptions",
  "Location",
  "LocationAddress",
  "LoginUrl",
  "ManagedBotCreated",
  "ManagedBotUpdated",
  "MaskPosition",
  "MaybeInaccessibleMessage",
  "MenuButton",
  "MenuButtonCommands",
  "MenuButtonDefault",
  "MenuButtonWebApp",
  "Message",
  "MessageAutoDeleteTimerChanged",
  "MessageEntity",
  "MessageId",
  "MessageOrigin",
  "MessageOriginChannel",
  "MessageOriginChat",
  "MessageOriginHiddenUser",
  "MessageOriginUser",
  "MessageReactionCountUpdated",
  "MessageReactionUpdated",
  "OrderInfo",
  "OwnedGift",
  "OwnedGiftRegular",
  "OwnedGifts",
  "OwnedGiftUnique",
  "PaidMedia",
  "PaidMediaInfo",
  "PaidMediaPhoto",
  "PaidMediaPreview",
  "PaidMediaPurchased",
  "PaidMediaVideo",
  "PaidMessagePriceChanged",
  "PassportData",
  "PassportElementError",
  "PassportElementErrorDataField",
  "PassportElementErrorFile",
  "PassportElementErrorFiles",
  "PassportElementErrorFrontSide",
  "PassportElementErrorReverseSide",
  "PassportElementErrorSelfie",
  "PassportElementErrorTranslationFile",
  "PassportElementErrorTranslationFiles",
  "PassportElementErrorUnspecified",
  "PassportFile",
  "PhotoSize",
  "Poll",
  "PollAnswer",
  "PollOption",
  "PollOptionAdded",
  "PollOptionDeleted",
  "PreCheckoutQuery",
  "PreparedInlineMessage",
  "PreparedKeyboardButton",
  "ProximityAlertTriggered",
  "ReactionCount",
  "ReactionType",
  "ReactionTypeCustomEmoji",
  "ReactionTypeEmoji",
  "ReactionTypePaid",
  "RefundedPayment",
  "ReplyKeyboardMarkup",
  "ReplyKeyboardRemove",
  "ReplyParameters",
  "ResponseParameters",
  "RevenueWithdrawalState",
  "RevenueWithdrawalStateFailed",
  "RevenueWithdrawalStatePending",
  "RevenueWithdrawalStateSucceeded",
  "SentWebAppMessage",
  "SharedUser",
  "ShippingAddress",
  "ShippingOption",
  "ShippingQuery",
  "StarAmount",
  "StarTransaction",
  "StarTransactions",
  "Sticker",
  "StickerSet",
  "Story",
  "StoryArea",
  "StoryAreaPosition",
  "StoryAreaType",
  "StoryAreaTypeLink",
  "StoryAreaTypeLocation",
  "StoryAreaTypeSuggestedReaction",
  "StoryAreaTypeUniqueGift",
  "StoryAreaTypeWeather",
  "SuccessfulPayment",
  "SuggestedPostApprovalFailed",
  "SuggestedPostApproved",
  "SuggestedPostDeclined",
  "SuggestedPostInfo",
  "SuggestedPostPaid",
  "SuggestedPostParameters",
  "SuggestedPostPrice",
  "SuggestedPostRefunded",
  "SwitchInlineQueryChosenChat",
  "TextQuote",
  "TransactionPartner",
  "TransactionPartnerAffiliateProgram",
  "TransactionPartnerChat",
  "TransactionPartnerFragment",
  "TransactionPartnerOther",
  "TransactionPartnerTelegramAds",
  "TransactionPartnerTelegramApi",
  "TransactionPartnerUser",
  "UniqueGift",
  "UniqueGiftBackdrop",
  "UniqueGiftBackdropColors",
  "UniqueGiftColors",
  "UniqueGiftInfo",
  "UniqueGiftModel",
  "UniqueGiftSymbol",
  "Update",
  "User",
  "UserChatBoosts",
  "UserProfileAudios",
  "UserProfilePhotos",
  "UserRating",
  "UsersShared",
  "Venue",
  "Video",
  "VideoChatEnded",
  "VideoChatParticipantsInvited",
  "VideoChatScheduled",
  "VideoChatStarted",
  "VideoNote",
  "VideoQuality",
  "Voice",
  "WebAppData",
  "WebAppInfo",
  "WebhookInfo",
  "WriteAccessAllowed",
];
const officialMethodNames = new Set([
  ...gettingUpdatesMethods,
  ...updatingMessagesMethods,
  ...stickerMethods,
  ...inlineModeMethods,
  ...paymentMethods,
  ...telegramPassportMethods,
  ...gameMethods,
]);

const availableMethodNames = implementedMethods
  .map((method) => method.name)
  .filter((name) => !officialMethodNames.has(name));

export const sidebarGroups = {
  sections: [
    {
      label: "Getting updates",
      items: [
        { name: "Update", kind: "type" as const },
        ...gettingUpdatesMethods.map((name) => ({
          name,
          kind: "method" as const,
        })),
        { name: "WebhookInfo", kind: "type" as const },
      ],
    },
    {
      label: "Available types",
      items: generatedTypeNames.map((name) => ({
        name,
        kind: "type" as const,
      })),
    },
    {
      label: "Available methods",
      items: availableMethodNames.map((name) => ({
        name,
        kind: "method" as const,
      })),
    },
    {
      label: "Updating messages",
      items: updatingMessagesMethods.map((name) => ({
        name,
        kind: "method" as const,
      })),
    },
    {
      label: "Stickers",
      items: stickerMethods.map((name) => ({
        name,
        kind: "method" as const,
      })),
    },
    {
      label: "Inline mode",
      items: inlineModeMethods.map((name) => ({
        name,
        kind: "method" as const,
      })),
    },
    {
      label: "Payments",
      items: paymentMethods.map((name) => ({
        name,
        kind: "method" as const,
      })),
    },
    {
      label: "Telegram Passport",
      items: telegramPassportMethods.map((name) => ({
        name,
        kind: "method" as const,
      })),
    },
    {
      label: "Games",
      items: gameMethods.map((name) => ({ name, kind: "method" as const })),
    },
  ],
};

export const completeMethodNames = implementedMethods.map(
  (method) => method.name,
);
